# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"

    config.vm.box_check_update = true

    config.vm.synced_folder "../deps/zgoubi", "/zgoubi"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y  build-essential gfortran valgrind tmux htop vim-nox \
            python-dev python-pip python-virtualenv
    SHELL
end
