from __future__ import absolute_import, division, print_function
import subprocess

DIFF = 'diff'

def compare_results_format(filename_original, filename_new, diff_output):
    '''
    Generates a diff between `filename_original` and `filename_new` and stores the
    output in `diff_output`.

    Args:
        filename_original (str)
        filename_new (str)
        diff_output (file)
    '''

    # Uses diff to check differences between the golden standard .res file
    # and the res file generated by running zgoubi.
    # So far running the same experiment yields the same numerical values without issue
    # The only part that changes are lines that record start, end and CPU time, those are
    # ignored via '-I'
    p = subprocess.Popen(
        [
            DIFF, '-ICPU', '-I[JobOB]',
            filename_original,
            filename_new,

        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )

    out, err = p.communicate()
    diff_output.write(out)
